@url=http://localhost:5000
@suffix=api/v1
@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5pQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzI4MzE3MTA1LCJleHAiOjE3Mjg0MDM1MDV9.3xx6ehWzP-jZM25XcFuGY_uNwaleIrL2m4wEl7esmFk

GET {{url}}

###
GET {{url}}/{{suffix}}/administrators?email=nguyenvana@gmail.com
authorization: bearer {{accessToken}}

# GET {{url}}/{{suffix}}/users?searchTerm=nu

###
POST {{url}}/{{suffix}}/administrators/add
Content-Type: application/json

{
  "full_name" : "Rimon",
  "phone_number":"0123456789",
  "email":"nim@gmail.com",
  "role": "admin",
  "password" :"123456789"
}

###
POST {{url}}/{{suffix}}/administrators/login
Content-Type: application/json

{
  "email":"ni@gmail.com",
  "password" :"123456789"
}